### PR TITLE
Pass handlebars instance to helpers

### PR DESCRIPTION
**Pull request by mucsi96**

### CODE REVIEW

**Comment by dominicbarnes** [comment]
What exactly is this PR accomplishing? It's generally good practice to provide a description of the problem you are solving, in addition to how your proposal solves that problem.

Why is having the `handlebars` object so important for a helper? If you need access to `SafeString`, you can do something like this:

```js
var handlebars = require('handlebars');

exports.safe = function () {
  return new handlebars.SafeString('<b>Hello World</b>');
};
```

Also, you shouldn't bump version numbers and modify changelogs in a PR. As the package maintainer, I will take care of those types of things.

**Comment by mucsi96** [comment]
Sorry I just wanted to create a complete solution. The problem with requiring handlebars from helper module is that if I use 'koa-handlebars' I don't depend directly on handlebars. So I can't access it that way. If I add handlebars as dependency to my project there will be two different handlebars versions. And this is not good. I think 'koa-handlebars' should have handlebars as peer dependency and my project should depend on it directly.

**Comment by dominicbarnes** [comment]
Yeah, the peer dependency route may be the best idea overall. I'll need to consider the implications to the API though.

In the meantime, what is wrong with adding handlebars as a dependency to your project? If I'm not mistaken, npm will de-duplicate if you're using compatible versions anyways. I just noticed that handlebars has published v4, so I'll need to look into upgrading this lib!

One other option, albeit the least pretty, is to just use a custom `SafeString` object. It turns out that handlebars [only looks for a `.toHTML()` method](https://github.com/wycats/handlebars.js/blob/0aef72cb8ee694911952d5447b08349a952aee90/lib/handlebars/utils.js#L67-L68), so you can create your own thin wrapper: (this actually could easily be a small npm module if you're interested in publishing one!)

```js
// safe.js
module.exports = function (str) {
  return {
    toHTML: function () { return str; }
  };
};

// helpers.js
var safe = require('./safe');

exports.hello = function () {
  return safe('<b>Hello World</b>');
};
```

**Comment by mucsi96** [comment]
Cool! Thanks!

**Pull request closed without merging**
